### ISSUE TITLE
include_recipe 'atom' does not install Atom on Ubuntu 20.04

### ISSUE THREAD

**Issue by Frikster** [sous-chefs/atom#67]
### :speaking_head: Foreword

Am brand new to Chef. Apologies if I'm missing something trivial.

## :ghost: Brief Description

`include_recipe 'atom'` leads to errors since it looks like there is no Atom release candidate for Ubuntu 20.04 Focal Fossa.

Summary:

- `STDERR: E: The repository 'http://ppa.launchpad.net/webupd8team/atom/ubuntu focal Release' does not have a Release file.`
- `No candidate version available for atom`
- `Error executing action 'install' on resource 'apt_package[atom]'`

Full trace:
```
        virtualbox-iso:       Reading package lists...
        virtualbox-iso:       STDERR: E: The repository 'http://ppa.launchpad.net/webupd8team/atom/ubuntu focal Release' does not have a Release file.
        virtualbox-iso:       ---- End output of ["apt-get", "-q", "update"] ----
        virtualbox-iso:       Ran ["apt-get", "-q", "update"] returned 100
        virtualbox-iso:
        virtualbox-iso:       Resource Declaration:
        virtualbox-iso:       ---------------------
        virtualbox-iso:       # In /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.15.6/lib/chef/provider/apt_repository.rb
        virtualbox-iso: 
        virtualbox-iso:        58:         declare_resource(:apt_update, new_resource.name) do
        virtualbox-iso:        59:           ignore_failure true
        virtualbox-iso:        60:           action :nothing
        virtualbox-iso:        61:         end
        virtualbox-iso:        62:
        virtualbox-iso: 
        virtualbox-iso:       Compiled Resource:
        virtualbox-iso:       ------------------
        virtualbox-iso:       # Declared in /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.15.6/lib/chef/provider/apt_repository.rb:58:in `block in <class:AptRepository>'
        virtualbox-iso: 
        virtualbox-iso:       apt_update("atom-ppa") do
        virtualbox-iso:         action [:nothing]
        virtualbox-iso:         default_guard_interpreter :default
        virtualbox-iso:         declared_type :apt_update
        virtualbox-iso:         cookbook_name "atom"
        virtualbox-iso:         ignore_failure true
        virtualbox-iso:       end
        virtualbox-iso:       Get:15 http://archive.ubuntu.com/ubuntu focal/main DEP-11 64x64 Icons [163 kB]
        virtualbox-iso:       Get:16 http://archive.ubuntu.com/ubuntu focal/universe amd64 DEP-11 Metadata [3603 kB]
        virtualbox-iso:       Get:17 http://archive.ubuntu.com/ubuntu focal/universe DEP-11 48x48 Icons [3016 kB]
        virtualbox-iso:       Get:18 http://archive.ubuntu.com/ubuntu focal/universe DEP-11 64x64 Icons [7794 kB]
        virtualbox-iso:       Get:19 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 DEP-11 Metadata [48.4 kB]
        virtualbox-iso:       Get:20 http://archive.ubuntu.com/ubuntu focal/multiverse DEP-11 48x48 Icons [23.1 kB]
        virtualbox-iso:       Get:21 http://archive.ubuntu.com/ubuntu focal/multiverse DEP-11 64x64 Icons [192 kB]
        virtualbox-iso:       Get:22 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 DEP-11 Metadata [264 kB]
        virtualbox-iso:       Get:23 http://archive.ubuntu.com/ubuntu focal-updates/main DEP-11 48x48 Icons [55.6 kB]
        virtualbox-iso:       Get:24 http://archive.ubuntu.com/ubuntu focal-updates/main DEP-11 64x64 Icons [87.9 kB]
        virtualbox-iso:       Get:25 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 DEP-11 Metadata [303 kB]
        virtualbox-iso:       Get:26 http://archive.ubuntu.com/ubuntu focal-updates/universe DEP-11 48x48 Icons [200 kB]
        virtualbox-iso:       Get:27 http://archive.ubuntu.com/ubuntu focal-updates/universe DEP-11 64x64 Icons [356 kB]
        virtualbox-iso:       Get:28 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 DEP-11 Metadata [2468 B]
        virtualbox-iso:       Get:29 http://archive.ubuntu.com/ubuntu focal-updates/multiverse DEP-11 48x48 Icons [29 B]
        virtualbox-iso:       Get:30 http://archive.ubuntu.com/ubuntu focal-updates/multiverse DEP-11 64x64 Icons [2638 B]
        virtualbox-iso:       Get:31 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 DEP-11 Metadata [1768 B]
        virtualbox-iso:       Get:32 http://archive.ubuntu.com/ubuntu focal-backports/universe DEP-11 48x48 Icons [2809 B]
        virtualbox-iso:       Get:33 http://archive.ubuntu.com/ubuntu focal-backports/universe DEP-11 64x64 Icons [3944 B]
        virtualbox-iso:       Reading package lists...
        virtualbox-iso:       STDERR: E: The repository 'http://ppa.launchpad.net/webupd8team/atom/ubuntu focal Release' does not have a Release file.
        virtualbox-iso:       ---- End output of ["apt-get", "-q", "update"] ----
        virtualbox-iso:       Ran ["apt-get", "-q", "update"] returned 100
        virtualbox-iso:
        virtualbox-iso:       Resource Declaration:
        virtualbox-iso:       ---------------------
        virtualbox-iso:       # In /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.15.6/lib/chef/provider/apt_repository.rb
        virtualbox-iso: 
        virtualbox-iso:        58:         declare_resource(:apt_update, new_resource.name) do
        virtualbox-iso:        59:           ignore_failure true
        virtualbox-iso:        60:           action :nothing
        virtualbox-iso:        61:         end
        virtualbox-iso:        62:
        virtualbox-iso: 
        virtualbox-iso:       Compiled Resource:
        virtualbox-iso:       ------------------
        virtualbox-iso:       # Declared in /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.15.6/lib/chef/provider/apt_repository.rb:58:in `block in <class:AptRepository>'
        virtualbox-iso: 
        virtualbox-iso:       apt_update("atom-ppa") do
        virtualbox-iso:         action [:nothing]
        virtualbox-iso:         default_guard_interpreter :default
        virtualbox-iso:         declared_type :apt_update
        virtualbox-iso:         cookbook_name "atom"
        virtualbox-iso:         ignore_failure true
        virtualbox-iso:       end
        virtualbox-iso: 
        virtualbox-iso:       System Info:
        virtualbox-iso:       ------------
        virtualbox-iso:       chef_version=14.15.6
        virtualbox-iso:       platform=ubuntu
        virtualbox-iso:       platform_version=20.04
        virtualbox-iso:       ruby=ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux]
        virtualbox-iso:       program_name=/usr/bin/chef-client
        virtualbox-iso:       executable=/opt/chef/bin/chef-client
        virtualbox-iso:
        virtualbox-iso: 
        virtualbox-iso:   * apt_package[atom] action install
        virtualbox-iso:     * No candidate version available for atom
        virtualbox-iso:     ================================================================================
        virtualbox-iso:     Error executing action `install` on resource 'apt_package[atom]'
        virtualbox-iso:     ================================================================================
        virtualbox-iso:
        virtualbox-iso:     Chef::Exceptions::Package
        virtualbox-iso:     -------------------------
        virtualbox-iso:     No candidate version available for atom
        virtualbox-iso:
        virtualbox-iso:     Resource Declaration:
        virtualbox-iso:     ---------------------
        virtualbox-iso:     # In /var/chef/cache/cookbooks/atom/recipes/debian.rb
        virtualbox-iso: 
        virtualbox-iso:      23: package 'atom'
        virtualbox-iso: 
        virtualbox-iso:     Compiled Resource:
        virtualbox-iso:     ------------------
        virtualbox-iso:     # Declared in /var/chef/cache/cookbooks/atom/recipes/debian.rb:23:in `from_file'
        virtualbox-iso: 
        virtualbox-iso:     apt_package("atom") do
        virtualbox-iso:       package_name "atom"
        virtualbox-iso:       action [:install]
        virtualbox-iso:       default_guard_interpreter :default
        virtualbox-iso:       declared_type :package
        virtualbox-iso:       cookbook_name "atom"
        virtualbox-iso:       recipe_name "debian"
        virtualbox-iso:     end
```

`No candidate version available for atom` on Ubuntu 20.04

## :pancakes: Cookbook version

0.4.0

## :woman_cook:  Chef-Infra Version

chef_version=14.15.6

## :tophat: Platform details
platform=ubuntu
platform_version=20.04
ruby=ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux]

## Steps To Reproduce

Just try `include_recipe 'atom'` on Ubuntu 20.04

## :police_car: Expected behavior

There are working instructions [here](https://linuxize.com/post/how-to-install-atom-text-editor-on-ubuntu-20-04/) using apt and packagecloud instead of webupd8team. Given a working solution exists (tested, it works for me) where I can install Atom for Ubuntu 20.04 manually I'd expect this recipe to have some support somehow to install Atom on Ubuntu 20.04.

## :heavy_plus_sign: Additional context

Likely just a sidenote but using the packagecloud recipe to install Atom has [problems of its own](https://github.com/computology/packagecloud-cookbook/issues/60)

I did also try manually changing the [debian recipe](https://github.com/sous-chefs/atom/blob/master/recipes/debian.rb) to this just so I can have something working:

```
apt_repository 'atom-ppa' do
  uri 'ppa:webupd8team/atom'
  distribution  'bionic'
end
```

This does lead to an installation and at first I thought things were working but this is the error message I get when I try to run Atom:

![image](https://user-images.githubusercontent.com/10172142/113659573-2a3e9e00-9657-11eb-8e69-33b55d613166.png)

Looks like a [known problem](https://github.com/electron/electron/issues/20348) solved [here](https://github.com/electron/electron/issues/20348#issuecomment-691533215). Once again solved using packagecloud. I have been trying and failing to modify the source further to source it from packagecloud. I tried modifying the [debian recipe](https://github.com/sous-chefs/atom/blob/master/recipes/debian.rb) further to:

```
apt_repository 'atom-ppa' do
  uri 'https://packagecloud.io/AtomEditor/atom/any/'
  distribution 'bionic'
  arch 'amd64'
  keyserver 'packagecloud.io/AtomEditor/atom/gpgkey'
end
```

But this leads to:

- `STDERR: E: Malformed entry 1 in list file /etc/apt/sources.list.d/atom-ppa.list (Component)`
- `Error executing action `run` on resource 'execute[apt-cache gencaches]'`
- `Error executing action `run` on resource 'execute[apt-get -q update]'`
- `Error executing action `update` on resource 'apt_update[atom-ppa]'`
- `Error executing action `install` on resource 'apt_package[atom]'`

**Comment by MarkGibbons** [comment]
Thank you for the detailed report. It looks like another repository is needed for atom on ubuntu 20.04 as you pointed out. https://linuxize.com/post/how-to-install-atom-text-editor-on-ubuntu-20-04/ worked for me as a manual method.  I'll see if I can adapt the cookbook to use those instructions and add ubuntu 20.04 support.  I'll try to look at it before 4/13/2021.

**Comment by MarkGibbons** [comment]
#68 should support ubuntu 20.04.  I'm still working on packaging details.

**Comment by MarkGibbons** [comment]
#68 should have added support
